[package]
name = "is_cryptopunk_owner"
type = "bin"
authors = [""]
compiler_version = ">=0.28.0"

[dependencies]
ethereum_history_api = { path = "../../../../ethereum_history_api/circuits/lib" }
token = { path = "../../../ethereum/circuits/lib" }
