[workspace]
members = [
    "ethereum_history_api/circuits/lib",
    "ethereum_history_api/circuits/get_receipt",
    "ethereum_history_api/circuits/get_storage",
    "ethereum_history_api/circuits/get_account",
    "ethereum_history_api/circuits/get_header",
    "vlayer/ethereum/circuits/lib",
    "vlayer/examples/circuits/is_dao_worthy",
    "vlayer/examples/circuits/is_ape_owner",
    "vlayer/examples/circuits/is_cryptopunk_owner",
]
default-member = "ethereum_history_api/circuits/lib"
