[workspace]
members = [
    "ethereum/circuits/lib",
    "ethereum/circuits/get_receipt",
    "ethereum/circuits/get_storage",
    "ethereum/circuits/get_storage_recursive",
    "ethereum/circuits/get_account",
    "ethereum/circuits/get_header",
    "ethereum/circuits/get_transaction",
    "vlayer/ethereum/circuits/lib",
    "vlayer/examples/circuits/is_dao_worthy",
    "vlayer/examples/circuits/is_ape_owner",
    "vlayer/examples/circuits/is_crypto_punk_owner",
]
default-member = "ethereum/circuits/lib"
