[package]
name = "get_transaction"
type = "bin"
compiler_version = ">=0.30.0"

[dependencies]
ethereum = { path = "../lib" }
proof = { tag = "v0.1.6-4", git = "https://github.com/vlayer-xyz/noir-trie-proofs", directory = "lib" }
