# Proving premine state in block 0. Has a tree depth of 4
chain_id = "1"
block_no = "0"
address = ['0x8b', '0x50', '0x5E', '0x28', '0x71', '0xF7', '0xdE', '0xb7', '0xa6', '0x38', '0x95', '0x20', '0x8e', '0x82', '0x27', '0xdc', '0xAa', '0x1B', '0xff', '0x05']
